# Generated by Django 3.1.2 on 2020-11-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
