# Generated by Django 3.1.2 on 2020-11-22 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_upload_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upload_file',
            new_name='upload',
        ),
    ]
