# Generated by Django 3.1.2 on 2020-11-22 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201122_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upload',
            new_name='picture',
        ),
    ]
