# Generated by Django 3.1.2 on 2020-11-22 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201122_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='picture',
            new_name='Upload_file',
        ),
    ]
